version: "3"
services:
  debian:
    build:
      context: "${LOCAL_HOST_PATH}/debian"
      dockerfile: Dockerfile
      args:
        - USERNAME=${USERNAME}
    container_name: "${PROJECT_NAME}_debian"
    env_file: .env
    environment:
      TZ: Asia/Tokyo
    tty: true
    user: "${USERNAME}:${USERNAME}"
    volumes:
      - ${LOCAL_HOST_PATH}:/app
    working_dir: "/app"
